- name: Play variables
  hosts: localhost
  vars:
     URL1: play.example.com
     URL2: show.example.com
     URL3: Book.example.com
  tasks:
    - name: Print play variable
      ansible.builtin.debug:
        msg: URL1 = {{URL}}
        msg: URL2 = {{URL}}
        msg: URL3 = {{URL}}
